# fly.toml app configuration file generated for flowlog-api
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'flowlog-api'
primary_region = 'sjc'  # San Jose - change to your preferred region

# Note: Image is specified during deployment via --image flag
# [build]
#   image = 'ghcr.io/smiileyface/flowlog-api:latest'

[deploy]
  release_command = 'alembic upgrade head'  # Run migrations on deploy

[env]
  APP_NAME = "Flowlog"
  VERSION = "0.1.0"
  ENVIRONMENT = "production"
  DEBUG = "False"
  LOG_LEVEL = "INFO"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
